AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Two Lambda Functions behind single API GW.
  API GW is not declared.
  
Globals:
  Function:
    Runtime: python3.8
    Timeout: 3
    
Resources:
  WatchVideo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://project-code-resources/lambdas/WatchVideo.zip
      Handler: WatchVideo.lambda_handler
      # Policies: AWSLambdaExecute
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /watch
            Method: 'GET'
  SearchVideo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://project-code-resources/lambdas/WatchVideo.zip
      Handler: WatchVideo.lambda_handler
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /search
            Method: 'GET'

Outputs:
  # To reference IAM Role ARN created by SAM Lambda automatically
  RoleCreateByWatchVideoLambda:
    Value: !GetAtt WatchVideo.Arn
  RoleCreateBySearchVideoLambda:
    Value: !GetAtt SearchVideo.Arn
