AWSTemplateFormatVersion: 2010-09-09

Resources:
  
  SecretRds:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: RDS database secret
      Name: !Sub ${AWS::StackName}/database
      # GenerateSecretString:
      #   IncludeSpace: false
      # todo take value from parameters 
      SecretString: >
        {
          "username": "serve_db",
          "password": "serve_db",
          "engine": "postgres",
          "host": "serve-db-cluster.cluster-c7umrsreh09y.us-east-1.rds.amazonaws.com",
          "port": 5432,
          "dbClusterIdentifier": "serve-db-cluster"
        }
      # SecretString: !Sub >
      #   {
      #     "username": "${DbUsername}",
      #     "password": "${DbPassword}",
      #     "engine": "postgres",
      #     "host": "${DbCluster.Endpoint.Address}",
      #     "port": ${DbCluster.Endpoint.Port},
      #     "dbClusterIdentifier": "${AWS::StackName}-DBClusterIdentifier"
      #   }

  SecretRdsResourcePolicy:
      DependsOn: 
        - SecretRds
        # todo uncomment
        # - LambdaRoleToProcessMessage
      Type: AWS::SecretsManager::ResourcePolicy
      Properties:
        SecretId: !Ref SecretRds
        ResourcePolicy:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: 'secretsmanager:GetSecretValue'
            Resource: '*'
            Principal:
              ## Principal cannot have regex! It must be complete!
              AWS:
                # todo uncomment
                # - !GetAtt LambdaRoleToProcessMessage.Arn
                # todo comment
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            "Condition":
              ForAnyValue:StringEquals:
                secretsmanager:VersionStage: AWSCURRENT

  # SecretRdsAttachment:
  #       Type: AWS::SecretsManager::SecretTargetAttachment
  #       Properties:
  #         SecretId: !Ref MyRDSInstanceRotationSecret
  #         TargetId: !Ref MyDBInstance
  #         TargetType: AWS::RDS::DBCluster

  