AWSTemplateFormatVersion: 2010-09-09
Resources:

  StandardQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      KmsMasterKeyId: !Ref CustomerManagedKey
      ReceiveMessageWaitTimeSeconds: 20

  StandardQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    DependsOn: StandardQueue
    Properties:
      Queues: 
        - !Ref StandardQueue
      PolicyDocument:
        Statement: 
          - Sid: 'Allow S3 to send message'
            Action: 
              - "SQS:SendMessage"
            Effect: "Allow"
            Resource: !Join 
              - ''
              - - !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:'
                - !GetAtt StandardQueue.QueueName
            Principal:  
              AWS: '*'
            Condition:
              StringEquals:
                aws:SourceAccount: !Sub '${AWS::AccountId}'
              ArnLike:
                aws:SourceArn: !Join 
                  - ''
                  - - 'arn:aws:s3:*:*:'
                    # - !Ref s3bucket
                    - 'vies'
